# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c6af7d2f7c4d883fff26a037c0b062a5afb23ecd47854bca02caff1a9e2f393268de3c11b0f02ba1c1260a257145fa4334ec5040ace6bdad1f9c6bdd3d6e8ea

test:
  secret_key_base: fbf1324881fa5db72d4001f03c7809ad0beb64991871529192b05744e4f1a6d06051bd0a6c8be3a026536b427d22309b7edbd50d089334f8ec9ccf794808390b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
